kind: pipeline
type: docker
name: default

steps:
  - name: deploy
    image: appleboy/drone-ssh

    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USERNAME
      password:
        from_secret: SSH_PASSWORD
      port:
        from_secret: SSH_PORT
      script:
        - cd /root/papyan
        - source ~/.nvm/nvm.sh
        - nvm use 22
        - git pull origin main
        - npm ci
        - npm run build
        - pm2 restart front

  - name: notify
    image: appleboy/drone-telegram:1.3.10
    settings:
      token:
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_CHAT_ID
      message: |
        ✅ Успешно развернуто приложение после коммита на ветке main!
        📝 Коммит: ${DRONE_COMMIT_MESSAGE}
        👤 Автор: ${DRONE_COMMIT_AUTHOR}
        🔗 [Посмотреть изменения](https://github.com/Vadim4ick/papyan/commit/${DRONE_COMMIT_SHA})

trigger:
  event:
    - push
    - promote
    - custom
