kind: pipeline
type: docker
name: default

steps:
  # - name: lint
  #   image: node:20
  #   commands:
  #     - npm ci
  #     - npm run lint
  - name: deploy
    image: appleboy/drone-ssh

    settings:
      host: 147.45.246.176
      username: root
      password: ch4A#3UJ7y*4A*
      port: 22
      script:
        - cd /root/papyan
        - source ~/.nvm/nvm.sh
        - nvm use 22
        - git pull origin main
        - npm ci
        - npm run build
        - pm2 restart front

  - name: notify
    image: appleboy/drone-telegram:1.3.10
    settings:
      token:
        from_secret: telegram_token
      to: 800465831
      message: |
        ✅ Успешно развернуто приложение после коммита на ветке main!
        📝 Коммит: ${DRONE_COMMIT_MESSAGE}
        👤 Автор: ${DRONE_COMMIT_AUTHOR}
        🔗 [Посмотреть изменения](https://github.com/ваш-репозиторий/commit/${DRONE_COMMIT_SHA})

trigger:
  event:
    - push
    - promote
    - custom
# trigger:
#   branch:
#     - master
#   event:
#     - push

