query GetHomePage {
  home_page {
    id

    mainBaner {
      ...MediaFragment
    }

    sliderClinik {
      directus_files_id {
        ...MediaFragment
      }
    }

    mainSlider {
      directus_files_id {
        ...MediaFragment
      }
    }
  }
}
