query GetProblems {
  problems {
    slider {
      problems_slide_id {
        id
        title
        img {
          ...MediaFragment
        }
      }
    }

      blocks {
        id

        problems_block_id {
          id
          title
          subtitle
          services {
            id
            services_id {
              ...ServiceFragment
            }
          }
        }
    }
  }
}

