query GetServiceClinic {
  servicesClinic {
    servicesClinic {
      servicesBlock_id {
        title
        img {
          ...MediaFragment
        }
        allServices {
          ...ServiceFragment
        }
      }
    }
  }
}
