query GetServiceClinic {
  servicesClinic {
    title
    description
    servicesClinic {
      servicesBlock_id {
        ...ServiceBlockFragment
      }
    }
    dopServices {
      servicesBlock_id {
        ...ServiceBlockFragment
      }
    }
  }
}
